# Just install and run gulp

matrix:
  include:
    - language: csharp
    - before_script:
        - dotnet restore
        - dotnet test
    - dotnet: 2.2.104
    - script:
        - dotnet publish -c Release -r win10-x64 -o dist
