# Just install and run gulp

matrix:
  include:
    - language: csharp
      before_script:
        - dotnet restore
        - dotnet test
      dist: xenial
      dotnet: 2.2
      mono: none
      script:
        - dotnet publish -c Release -r win10-x64 -o dist
    - language: node_js
      env:
      - CHROME_BIN=chromium-browser
      node_js: 
      - "node"
      - "9"
      addons:
        chrome: stable
      before_script:
        - cd kadmium-dmx.Webui
        - npm install
        - npm install -g @angular/cli
      script:
        - npm run test-headless
        - ng build -c production --output-path dist
