version: '3.6'
services:
    kadmium-dmx:
        restart: unless-stopped
        image: kadmium/kadmium-dmx
        deploy:
            mode: global
            restart_policy:
                condition: none
        volumes:
            - 'kadmium-dmx-volume:C:/app/kadmium-dmx-webapi/kadmium-dmx/data'
        ports:
            - '5000:5000'
            - '9001:9001/udp'
        networks:
            - default
    mongo:
        restart: unless-stopped
        image: 'mongo:latest'
        deploy:
            mode: global
            restart_policy:
                condition: none
        volumes:
            - 'mongo-db:C:/data/db'
        ports:
            - '27017:27017'
        networks:
            - default
volumes:
    kadmium-dmx-volume: null
    mongo-db: null
networks:
    default: null
