version: "3.6"
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    deploy:
      mode: global
      restart_policy:
        condition: none
    ports:
      - 32768:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example